/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    BottleHelperCard: typeof import('./components/cards/BottleHelperCard.vue')['default']
    BoxHelperCard: typeof import('./components/cards/BoxHelperCard.vue')['default']
    ConsumptionProgressCard: typeof import('./components/cards/ConsumptionProgressCard.vue')['default']
    DailyTaskCard: typeof import('./components/DailyTaskCard.vue')['default']
    DailyTaskStatus: typeof import('./components/DailyTaskStatus.vue')['default']
    DreamHelperCard: typeof import('./components/cards/DreamHelperCard.vue')['default']
    FightHelperCard: typeof import('./components/cards/FightHelperCard.vue')['default']
    FishHelperCard: typeof import('./components/cards/FishHelperCard.vue')['default']
    GameStatus: typeof import('./components/GameStatus.vue')['default']
    HangUpStatusCard: typeof import('./components/cards/HangUpStatusCard.vue')['default']
    HeroUpgradeCard: typeof import('./components/cards/HeroUpgradeCard.vue')['default']
    IdentityCard: typeof import('./components/Common/IdentityCard.vue')['default']
    MessageTester: typeof import('./components/MessageTester.vue')['default']
    MonthlyTasksCard: typeof import('./components/cards/MonthlyTasksCard.vue')['default']
    MyCard: typeof import('./components/Common/MyCard.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NButtonGroup: typeof import('naive-ui')['NButtonGroup']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    NDialogProvider: typeof import('naive-ui')['NDialogProvider']
    NDropdown: typeof import('naive-ui')['NDropdown']
    NIcon: typeof import('naive-ui')['NIcon']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NLoadingBarProvider: typeof import('naive-ui')['NLoadingBarProvider']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NModal: typeof import('naive-ui')['NModal']
    NNotificationProvider: typeof import('naive-ui')['NNotificationProvider']
    NProgress: typeof import('naive-ui')['NProgress']
    NSelect: typeof import('naive-ui')['NSelect']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    RecruitHelperCard: typeof import('./components/cards/RecruitHelperCard.vue')['default']
    RoleProfileCard: typeof import('./components/RoleProfileCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StarUpgradeCard: typeof import('./components/cards/StarUpgradeCard.vue')['default']
    StudyChallengeCard: typeof import('./components/cards/StudyChallengeCard.vue')['default']
    TeamStatus: typeof import('./components/TeamStatus.vue')['default']
    ThemeToggle: typeof import('./components/Common/ThemeToggle.vue')['default']
    TokenManager: typeof import('./components/TokenManager.vue')['default']
    TowerStatus: typeof import('./components/TowerStatus.vue')['default']
    WebSocketTester: typeof import('./components/WebSocketTester.vue')['default']
  }
}
